volumes:
    elastic:
        driver: local
services:
    Transcendence:
        container_name: Transcendence
        image: docker.elastic.co/beats/filebeat:8.17.0
        restart: unless-stopped
        volumes:
          - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
          - ./access.log:/var/log/apache2/access.log
        command: filebeat -e
        depends_on:
          - logstash
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:8.17.0
        restart: unless-stopped
        volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        depends_on:
          - elasticsearch
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
        volumes:
          - elastic:/usr/share/elasticsearch/data
          - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        restart: unless-stopped
    kibana:
        image: docker.elastic.co/kibana/kibana:8.17.0
        container_name: kibana
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch
        restart: unless-stopped
