services:
    Transcendence:
        container_name: Transcendence
        image: docker.elastic.co/beats/filebeat:8.17.0
        restart: unless-stopped
        volumes:
          - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
          - ./access.log:/var/log/apache2/access.log
        command: filebeat -e
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:8.17.0
        restart: unless-stopped
        volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        depends_on:
          - Transcendence
